version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pi-hole
    mac_address: d0:ca:ab:cd:ef:01
    cap_add:
      - NET_ADMIN
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      # - 67/udp # Uncomment if you want to use Pi-Hole for DHCP
      - 80/tcp
      - 22/tcp
    environment:
      ServerIP: 192.168.0.195
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: 192.168.0.196
    volumes:
      - /volume1/docker/pihole-unbound/pihole/volume:/etc/pihole:rw
      - /volume1/docker/pihole-unbound/pihole/config/hosts:/etc/hosts:ro
      - /volume1/docker/pihole-unbound/pihole/config/resolv.conf:/etc/resolv.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
      - /volume1/docker/pihole-unbound/pihole/config/pihole-FTL.conf:/etc/pihole/pihole-FTL.conf:ro
    networks:
      home:
        ipv4_address: 192.168.0.195
    restart: always
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    hostname: syn-unbound
    mac_address: d0:ca:ab:cd:ef:02
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.0.196
    restart: always

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /volume1/docker/radarr:/config
      - /volume1/downloads/movies:/downloads
      - /volume1/movies:/movies
    environment:
      - TZ=Europe/Paris

 sonarr:
   container_name: sonarr
   image: linuxserver/sonarr
   restart: unless-stopped
   ports:
     - 8989:8989
   volumes:
     - /volume1/docker/sonarr:/config
     - /volume1/downloads/series:/downloads
     - /volume1/series:/tv
   environment:
     - TZ=Europe/Paris

 jackett:
   container_name: jackett
   image: linuxserver/jackett
   restart: unless-stopped
   ports:
     - 9117:9117
   volumes:
     - /volume1/docker/jackett:/config
   environment:
     - TZ=Europe/Paris

  # auto update service
  # https://github.com/v2tec/watchtower
  watchtower:
    image: v2tec/watchtower
    restart: always
    command: --label-enable --cleanup
    logging:
      options:
        max-size: 10m
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_bond0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.195/30 # 192.168.1.5 and 192.168.1.6
